# Not used but might be in the future
# build environment
FROM node:alpine as builder
WORKDIR /client
#ENV PATH /client/node_modules/.bin:$PATH
COPY package*.json ./
RUN yarn install --production=true
COPY . ./
RUN yarn run build

# production environment
FROM nginx:stable-alpine
COPY --from=builder /client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]