# Dev conf file no production
version: "3.7"
services:
  client:
    image: himo-client
    container_name: himo-react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/client
      - /client/node_modules
    ports:
      - 80:3000
    command: yarn start
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - api
    networks:
      - app-network
  api:
    image: himo-api
    container_name: himo-node-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
      - ./commons:/commons
      - /api/node_modules
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://mongo/db
    ports:
      - 9000:9000
    command: npm run dev
    networks:
      - app-network

  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: example