# Base conf file
version: "3.7"

services:
  app:
    image: himo-app
    container_name: himo-node-app
    build:
      context: .
    volumes:
    - /app/node_modules
    - /commons/node_modules

    depends_on:
      - mongo
    networks:
      - app-network

  bot:
    image: himo-bot
    container_name: himo-node-bot
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
    - /bot/node_modules
    - /commons/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge