# Prod conf file
version: "3.7"
services:

  app:
    build:
      dockerfile: ./app/Dockerfile.prod
    volumes:
    - /app/client/node_modules
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongo/db
      REACT_PORT: 80
      API_PORT: 3000
#    expose:
#      - 3000
    ports:
      - 80:3000
    command: npm run start

#  bot:
#    image: himo-bot
#    container_name: himo-node-bot
#    build:
#      context: ./bot
#    volumes:
#      - ./bot:/bot
#      - ./commons:/commons
#      - /bot/node_modules
#    depends_on:
#      - mongo
#    environment:
#      NODE_ENV: production
#      MONGODB_URL: mongodb://mongo/db
##      INSTANCE_SCALING_MIN: 0
#    ports:
#      - 8889:8889
#    command: npm run start
#    networks:
#      - app-network

  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    restart: always
    networks:
      - app-network

volumes:
  data-volume:
  node_modules:
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: example