# Prod build environment for react + node express app

FROM node:alpine

# Copy common folder
WORKDIR /commons
COPY ./commons/package*.json ./
RUN npm install --silent
COPY ./commons .

# Create App Directory
WORKDIR /app

# Install Dependencies
COPY ./app/package*.json ./
RUN ls
RUN npm install --silent

# Copy app source code
COPY ./app .

# Build react app
WORKDIR /app/client
#COPY package*.json ./
RUN ls
RUN yarn install
#RUN npm install react-scripts@3.4.1 -g --silent
#COPY . ./
RUN npm run build

# Copy build to static folder
WORKDIR /app
RUN mkdir -p /static
RUN mv ./client/build ./static
RUN rm -r ./client

# Start node js server
CMD ["npm","start"]