# Prod build environment for react + node express app

FROM node:alpine

# Copy common folder
WORKDIR /commons
COPY ../commons/package*.json ./
RUN npm install --silent --only=production
COPY ../commons .

# Create App Directory
WORKDIR /api

# Install Dependencies
COPY package*.json ./
RUN npm install --silent --only=production

# Copy app source code
COPY . .

# Start node js server
CMD ["npm","start"]